// Code generated by mockery v2.33.0. DO NOT EDIT.

package apipkg

import (
	config "jagaad-backend-test/config"
	entities "jagaad-backend-test/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockIFetch is an autogenerated mock type for the IFetch type
type MockIFetch struct {
	mock.Mock
}

// FetchUsersFromAPI provides a mock function with given fields: conf
func (_m *MockIFetch) FetchUsersFromAPI(conf config.Config) []entities.User {
	ret := _m.Called(conf)

	var r0 []entities.User
	if rf, ok := ret.Get(0).(func(config.Config) []entities.User); ok {
		r0 = rf(conf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.User)
		}
	}

	return r0
}

// NewMockIFetch creates a new instance of MockIFetch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFetch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFetch {
	mock := &MockIFetch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
